name: Pipeline de CI/CD

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    validate:
        name: 1. Validar Calidad del Código
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del código
              uses: actions/checkout@v4
            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'
            - name: Instalar Dependencias
              run: npm install
            - name: Ejecutar Pruebas y Linter
              run: |
                npm run lint
                npm run test